#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-editor
Version  : 0.5
Release  : 6
URL      : https://pypi.python.org/packages/source/p/python-editor/python-editor-0.5.tar.gz
Source0  : https://pypi.python.org/packages/source/p/python-editor/python-editor-0.5.tar.gz
Summary  : Programmatically open an editor, capture the result.
Group    : Development/Tools
License  : Apache-2.0
Requires: python-editor-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
`python-editor` is a library that provides the `editor` module for programmatically
interfacing with your system's $EDITOR.

%package python
Summary: python components for the python-editor package.
Group: Default

%description python
python components for the python-editor package.


%prep
%setup -q -n python-editor-0.5

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
